# Generated by Django 4.2.16 on 2024-10-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgpdgeneralterm',
            old_name='term_type',
            new_name='term_itens',
        ),
        migrations.RemoveField(
            model_name='lgpdtermitem',
            name='is_mandatory',
        ),
    ]
