# Generated by Django 4.2.16 on 2024-10-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_lgpdusertermapproval_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgpdtermitem',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='lgpdtermitem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
