# Generated by Django 4.2.16 on 2024-10-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_rename_name_lgpdtermitem_title_lgpdtermitem_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgpdgeneralterm',
            name='term_itens',
        ),
        migrations.AddField(
            model_name='lgpdgeneralterm',
            name='term_itens',
            field=models.ManyToManyField(blank=True, related_name='general_terms', to='user_management.lgpdtermitem'),
        ),
    ]
