# Generated by Django 4.2.16 on 2024-10-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_lgpdgeneralterm_term_itens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgpdusertermapproval',
            name='term_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
