# Generated by Django 4.2.16 on 2024-11-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_lgpdusertermapproval_term_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lgpdusertermapproval',
            name='term_name',
        ),
        migrations.AddField(
            model_name='lgpdusertermapproval',
            name='items_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.lgpdtermitem'),
        ),
    ]
