# Generated by Django 3.1.3 on 2024-09-27 01:03

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsParts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('contact_phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Paymasters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('email_primary', models.EmailField(max_length=254, unique=True)),
                ('email_secondary', models.EmailField(max_length=254, unique=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('paymaster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymasters')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAuthorizedThirdParties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorized_third_party_id', models.CharField(max_length=255, unique=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('state', models.CharField(max_length=255)),
                ('approved_at', models.DateField(null=True)),
                ('rejected_at', models.DateField(null=True)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participants')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTradeBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField(null=True)),
                ('nfe_number', models.CharField(max_length=255)),
                ('nfe_series', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('new_due_date', models.DateField(null=True)),
                ('ballast_kind', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
                ('payment_place', models.CharField(max_length=255)),
                ('update_reason_kind', models.CharField(max_length=255)),
                ('endorser_original_id', models.ForeignKey(db_column='endorser_original_id', on_delete=django.db.models.deletion.CASCADE, related_name='endorser_bills', to='core.assetsparts')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participants')),
                ('payer_id', models.ForeignKey(db_column='payer_id', on_delete=django.db.models.deletion.CASCADE, related_name='payer_bills', to='core.participants')),
            ],
        ),
        migrations.CreateModel(
            name='FkAuthorizedThirdPartyParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_third_party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participantauthorizedthirdparties')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participants')),
            ],
            options={
                'verbose_name': 'Authorized Third Party Participant',
                'verbose_name_plural': 'Authorized Third Party Participants',
                'unique_together': {('authorized_third_party_id', 'participant_id')},
            },
        ),
    ]
