# Generated by Django 3.1.3 on 2024-09-23 16:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGPDTerm',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('acceptance_date', models.DateTimeField(auto_now_add=True)),
                ('update_logs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='contato',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
