# Generated by Django 3.1.3 on 2024-10-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20241020_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_permissions',
        ),
    ]
