# Generated by Django 3.1.3 on 2024-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20240923_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
